magasin/urls.py
from django.urls import path,include
from . import views
from .views import CategoryAPIView
from rest_framework import routers
from magasin.views import  CategoryAPIView,ProduitAPIView,shop

from magasin.views import ProductViewset, CategoryAPIView
 
# Ici nous créons notre routeur
router = routers.SimpleRouter()
# Puis lui déclarons une url basée sur le mot clé ‘category’ et notre view
# afin que l’url générée soit celle que nous souhaitons ‘/api/category/’
router.register('produit', ProductViewset, basename='produit')


urlpatterns = [ 


                path('api/category/', CategoryAPIView.as_view()),
                path('api/produits/', ProduitAPIView.as_view()),
                path('api-auth/', include('rest_framework.urls')),

                path('api/', include(router.urls)),
                
                path('', views.index,name='index'),
                path('',views.home,name='home'),
                path('indexA', views.indexA, name='indexA'),
                
               
                path('nouveau_produit/',views.nouveau_produit, name='nouveau_produit'),
                path('nouveauFournisseur/',views. nouveauFournisseur, name='nouveauFournisseur'),
                path('modifier_produit/<int:pk>/', views.modifier_produit, name='modifier_produit'),
                path('supprimer_produit/<int:pk>/', views.supprimer_produit, name='supprimer_produit'),

                
                path('fournisseurs/', views.ListFournisseur, name='fournisseurs'),
                path('nouvFournisseur/',views.nouveauFournisseur,name='nouvFournisseur'),
                path('editFournisseur/<int:fk>/', views.edit_Fournisseur, name='edit_Fournisseur'),
                path('deleteFournisseur/<int:fk>/', views.delete_Fournisseur, name='delete_Fournisseur'),
                path('Fournisseur/<int:for_id>/', views.detail_Fournisseur, name='detail_Fournisseur'),

                #categorie 

                path('ListCategorie/', views.ListCategorie, name='ListCategorie'),
                path('create_categorie/',views.create_categorie,name='create_categorie'),
                path('editCategorie/<int:pk>/', views.edit_categorie, name='edit_categorie'),
                path('deleteCategorie/<int:pk>/', views.delete_categorie, name='delete_categorie'),
                path('Categorie/<int:categorie_id>/', views.detail_categorie, name='detail_categorie'),






                path('ListCommande/', views.ListCommande, name='ListCommande'),
                path('create_commande/',views.create_commande,name='create_commande'),
                path('editCommande/<int:pk>/', views.edit_commande, name='edit_commande'),
                path('deleteCommande/<int:pk>/', views.delete_commande, name='delete_commande'),
                path('Commande/<int:commande_id>/', views.detail_commande, name='detail_commande'),


                path('registurls.pyer/',views.register, name = 'register'),
                path('magasin/search/', views.search, name='search'),
                path('magasin/<int:pk>/', views.product_detail, name='product_detail'),
                
                path('shop/', shop, name='shop'),
                
            ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from magasin import views
from . import views

from rest_framework import routers
from magasin.views import ProductViewset, CategoryAPIView
 
# Ici nous créons notre routeur
router = routers.SimpleRouter()
# Puis lui déclarons une url basée sur le mot clé ‘category’ et notre view
# afin que l’url générée soit celle que nous souhaitons ‘/api/category/’
router.register('produit', ProductViewset, basename='produit')



urlpatterns = [

    path('api-auth/', include('rest_framework.urls', namespace='my_rest_framework')),
    path('api/', include(router.urls)),
    
    path('',views.index),
    path('admin/', admin.site.urls),
    path('magasin/',include('magasin.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name ='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'), name ='logout'),
    path('accounts/password_reset_complete/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/password_reset_confirm/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/password_reset_email/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_email.html'), name='password_reset_email'),
    path('accounts/password_reset/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    
]+static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

magasin/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
class Produit(models.Model):
    TYPE_CHOICES=[('em','emballé'),
              ('fr','frais'),
              ('cs','conservé')
              
              ]
    libellé = models.CharField(max_length=100)
    description = models.TextField(default='non definie')
    prix = models.DecimalField(max_digits=10, decimal_places=3)
    type = models.CharField(max_length=2,choices=TYPE_CHOICES,default='em')
    Categorie= models.ForeignKey('Categorie', on_delete=models.CASCADE, null=True)
    Fournisseur=models.ForeignKey('Fournisseur',on_delete=models.CASCADE,null=True)

    img=models.ImageField(blank=True,upload_to='media/')
    
    def __str__(self):
        return (self.libellé +","+self.description+","+str(self.prix)+"," +self.type )

class Categorie(models.Model):
    TYPE_CHOICES=[('AL','Alimentaire'),
                  ('Mb','Meuble'),
                  ('Sn','Sanitaire'),
                  ('Vs','Vaisselle'),
                  ('Vt','Vêtement'),
                  ('Jx','Jouets'),
                  ('Lg','Linge de Maison'),
                  ('Bj','Bijoux'),
                  ('Dc','Décor')
                  
                  ]
    name=models.CharField(max_length=50,default='Al',choices=TYPE_CHOICES)
    
    def __str__(self):
        return self.name
    
class Fournisseur(models.Model):
    nom = models.CharField(max_length=100, default='')
    adresse=models.TextField(null=True)
    email=models.EmailField(null=True)
    telephone=models.CharField(max_length=8)

    def __str__(self):
        return (self.nom+','+self.adresse+','+self.email+','+self.telephone)
class ProduitNC(Produit):
    Duree_garantie=models.CharField(max_length=100)
    
    def __str__(self):
        return "objet ProduitNC:%s"%(self.Duree_garantie)

class Commande(models.Model):
    dateCde=models.DateField(null=True,default=date.today)
    totalCde=models.DecimalField(max_digits=10,decimal_places=3)
    produits=models.ManyToManyField('Produit')
    def __str__(self):
        return str(self.dateCde) + ' - ' + str(self.totalCde)

magasin/views.py
from django.http import HttpResponse, HttpResponseRedirect
from . models import Produit,Commande,Fournisseur,Categorie
from .forms import ProduitForm,CommandeForm,CategorieForm
from django.shortcuts import get_object_or_404, redirect, render
from .forms import ProduitForm,UserCreationForm,FournisseurForm
from django.contrib.auth import login,authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.forms.models import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render


from rest_framework.views import APIView
from rest_framework.response import Response
from magasin.serializers import CategorySerializer,ProduitSerializer

from rest_framework import viewsets

from django.shortcuts import render
from django.contrib.auth.decorators import login_required




class ProductViewset(viewsets.ReadOnlyModelViewSet):

    serializer_class = ProduitSerializer

    def get_queryset(self):
        queryset = Produit.objects.filter(active=True)
        category_id = self.request.GET.get('category_id')
        if category_id:
            queryset = queryset.filter(categorie_id=category_id)
        return queryset



class CategoryAPIView(APIView):
 
    def get(self, *args, **kwargs):
        categories = Categorie.objects.all()
        serializer = CategorySerializer(categories, many=True)
        return Response(serializer.data)

class ProduitAPIView(APIView):
    def get(self, *args, **kwargs):
        produits = Produit.objects.all()
        serializer = ProduitSerializer(produits, many=True)
        return Response(serializer.data)

@login_required
def index(request):
    if request.user.is_authenticated:
        request.session['username'] = request.user.username
    return render(request, 'index.html')

def index(request):
    list=Produit.objects.all()
    return render(request,'magasin/vitrine.html',{'list':list})
def register(request):
    if request.method == 'POST' :
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request,user)
            messages.success(request, f'Coucou {username}, Votre compte a été créé avec succès !')
            return redirect('home')
    else :
        form = UserCreationForm()
    return render(request,'registration/register.html',{'form' : form})

def home(request):
    context={'val':"Menu Acceuil"}
    return render (request,'home.html',context)
def nouveau_produit(request):
 if request.method == "POST" :
    form = ProduitForm(request.POST,request.FILES)
    if form.is_valid():
        form.save()
        return HttpResponse('/magasin')
 else :
        form = ProduitForm() #créer formulaire vide
 return render(request,'magasin/majProduits.html',{'form':form})


def indexA(request):
     return render(request,'magasin/indexA.html' )


# vue pour modifier un produit existant
def modifier_produit(request, pk):
    produit = get_object_or_404(Produit,pk=pk)

    if request.method == "POST":
        form = ProduitForm(request.POST, request.FILES, instance=produit)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ProduitForm(instance=produit)

    return render(request,'magasin/majProduits.html', {'form': form})

# vue pour supprimer un produit existant
def supprimer_produit(request,pk):
    produit = get_object_or_404(Produit, pk=pk)

    if request.method == "POST":
        produit.delete()
        return redirect('index')

    return render(request, 'magasin/supprimerProduit.html', {'produit': produit})

def  nouveauFournisseur(request):
    if request.method == "POST" :
        form = FournisseurForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/magasin')
    else :
        form = FournisseurForm() #créer formulaire vide
    return render(request,'magasin/fournisseur.html',{'form':form})


def search(request):
    query = request.GET.get('q')
    if query:
        try:
            # Essayez de convertir la chaîne de requête en float pour la recherche par prix
            query = float(query)
            produits = Produit.objects.filter(prix=query)
        except ValueError:
            # Si la conversion en float échoue, recherchez par libellé, type ou catégorie
            produits = Produit.objects.filter(Q(type__icontains=query) )
        context = {'query': query, 'produits': produits}
        return render(request, 'magasin/search_results.html', context)
    else:
        return render(request, 'magasin/search_results.html')
   
def product_detail(request, pk):
    product = get_object_or_404(Produit, pk=pk)
    return render(request, 'magasin/detail_product.html', {'product': product})



#commande
def create_commande(request):
       if request.method == "POST" :
         form = CommandeForm(request.POST)
         if form.is_valid():
              form.save() 
              commandes=Commande.objects.all()
              
              return render(request,'magasin/Commandes/mesCommandes.html',{'commandes':commandes})
       else : 
            form = CommandeForm() #créer formulaire vide 
            commandes=Commande.objects.all()
            return render(request,'magasin/Commandes/create_commande.html',{'form':form,'commandes':commandes})

def edit_commande(request, pk):
    commande = get_object_or_404(Commande, pk=pk)
    if request.method == 'POST':
        form = CommandeForm(request.POST, instance=commande)
        if form.is_valid():
            form.save()
            return redirect('ListCommande')
    else:
        form = CommandeForm(instance=commande)
    return render(request, 'magasin/Commandes/edit_commande.html', {'form': form})

def delete_commande(request, pk):
    commande = get_object_or_404(Commande, pk=pk)
    if request.method == 'POST':
        commande.delete()
        return redirect('ListCommande')
    return render(request, 'magasin/Commandes/delete_commande.html', {'commande': commande})

def detail_commande(request, commande_id):
    commande = get_object_or_404(Commande, id=commande_id)
    context = {'commande': commande}
    return render(request, 'magasin/Commandes/detail_commande.html', context)

def ListCommande(request):
        commandes= Commande.objects.all()
        context={'commandes':commandes}
        return render( request,'magasin/Commandes/mesCommandes.html',context )

from django.shortcuts import redirect, render, get_object_or_404


#fournisseur

def ListFournisseur(request):
    fournisseurs = Fournisseur.objects.all()
    context = {'fournisseurs': fournisseurs}
    return render(request, 'magasin/Fournisseurs/mesFournisseurs.html', context)

def nouveauFournisseur(request):
    if request.method == "POST" :
         form = FournisseurForm(request.POST,request.FILES)
         if form.is_valid():
               # Récupérer l'instance du modèle produit
            frns = form.save(commit=False)
            # Récupérer la nouvelle image téléchargée
            nouvelle_image = form.cleaned_data['logo']
            # Si une nouvelle image a été téléchargée, la sauvegarder
            if nouvelle_image:
                frns.logo= nouvelle_image
            # Sauvegarder le produit
            form.save() 
            fournisseurs=Fournisseur.objects.all()
            return render(request,'magasin/Fournisseurs/mesFournisseurs.html',{'fournisseurs':fournisseurs})
    else : 
            form = FournisseurForm() #créer formulaire vide 
            fournisseurs=Fournisseur.objects.all()
            return render(request,'magasin/Fournisseurs/create_For.html',{'form':form,'fournisseurs':fournisseurs})

"""def Fournisseur_index(request):
    fournisseurs = Fournisseur.objects.all()
    context = {'fournisseurs': fournisseurs}
    return render(request, 'magasin/mesFournisseurs.html', context)
    if request.method == "POST" :
        form = FournisseurForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/magasin')
    else :
        form = FournisseurForm() #créer formulaire vide
    return render(request,'magasin/mesFournisseurs.html',{'form':form})"""
def edit_Fournisseur(request, fk):
    fournisseur = get_object_or_404(Fournisseur, id=fk)
    if request.method == 'POST':
        form = FournisseurForm(request.POST, request.FILES, instance=fournisseur)
        if form.is_valid():
            # Récupérer l'instance du modèle produit
            frns = form.save(commit=False)
            # Récupérer la nouvelle image téléchargée
            nouvelle_image = form.cleaned_data['logo']
            # Si une nouvelle image a été téléchargée, la sauvegarder
            if nouvelle_image:
                frns.logo= nouvelle_image
            # Sauvegarder le produit
            frns.save()
            return redirect('fournisseurs')
    else:
        form = FournisseurForm(instance=fournisseur)
        return render(request, 'magasin/Fournisseurs/edit_For.html', {'form': form})

def delete_Fournisseur(request, fk):
    fournisseur = get_object_or_404(Fournisseur, id=fk)
    if request.method == 'POST':
        fournisseur.delete()
        return redirect('fournisseurs')
    return render(request,'magasin/Fournisseurs/delete_For.html', {'fournisseur': fournisseur})

def detail_Fournisseur(request, for_id):
    fournisseur = get_object_or_404(Fournisseur, id=for_id)
    context = {'fournisseur': fournisseur}
    return render(request, 'magasin/Fournisseurs/detail_For.html', context)



#categorie

def create_categorie(request):
       if request.method == "POST" :
         form = CategorieForm(request.POST)
         if form.is_valid():

magasin/templates/magasin/acceuil.html
{% if request.session.username %}
    <p>Bienvenue, {{ request.session.username }}!</p>
{% else %}
    <p>Bienvenue, visiteur!</p>
{% endif %}

magasin/templates/magasin/base.html
{% load static %}

<!DOCTYPE html>
<html>

<meta charset='utf-8'>
<meta http-equiv='X-UA-Compatible' content='IE=edge'>
<title>
{% block title %} {% endblock %}
</title>
<link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/base.css'%}">
{% block styles %} {% endblock %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
crossorigin="anonymous"></script>

<head>

  <!-- Nav -->

  <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav1" aria-controls="navbarNav1" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
      <a class="navbar-brand" href="#">
        <strong>Navbar</strong>
      </a>

        <div class="collapse navbar-collapse" id="navbarNav1">
    <ul class="navbar-nav mr-auto">
      

      {% if user.is_authenticated and user.is_superuser %}
    <a class="nav-link"href="{% url 'admin:index' %}" >Accéder à l'administration</a>
       {% endif %}

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}"> Catalogue <span class="sr-only">(current)</span></a>
      </li>

      {% if user.is_authenticated and not user.is_staff %}
      <li class="nav-item  ">

        <a class="nav-link" href="{% url 'shop' %}">Panier</a>

      </li>
      {% endif %}
     
      {% if user.is_authenticated %}
      <li class="nav-item dropdown btn-group">
        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  href="{% url 'index' %}">Produits</a>
        <div class="dropdown-menu dropdown" aria-labelledby="dropdownMenu1">
          {% if user.is_authenticated and user.is_superuser %}
          <a class="dropdown-item" href="{% url 'nouveau_produit' %}"> Ajouter Produit</a>
          {% endif %}  
          <a class="dropdown-item" href="{% url 'index' %}">Liste des Produit</a>
        </div>
      </li>
      {% endif %} 


      {% if user.is_authenticated and user.is_superuser %}
        <li class="nav-item dropdown btn-group">
          <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
          <div class="dropdown-menu dropdown" aria-labelledby="dropdownMenu1">
            
            <a class="dropdown-item" href="{% url 'ListCategorie' %}">Categories</a>
              <a class="dropdown-item" href="{% url 'create_categorie' %}">Ajout Categorie</a>
          </div>
        </li>
        {% endif %}

        {% if user.is_authenticated and user.is_superuser %}
      <li class="nav-item dropdown btn-group">
        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Fournisseur</a>
        <div class="dropdown-menu dropdown" aria-labelledby="dropdownMenu1">
          
          <a class="dropdown-item" href="{% url 'nouveauFournisseur' %}">Ajout Fournisseur</a>
            <a class="dropdown-item" href="{% url 'fournisseurs' %}">List Fournisseur</a>
        </div>
      </li>
      {% endif %}


      {% if user.is_authenticated and user.is_superuser %}
      <li class="nav-item dropdown btn-group">
        <a class="nav-link dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Commandes</a>
        <div class="dropdown-menu dropdown" aria-labelledby="dropdownMenu1">
          
          <a class="dropdown-item" href="{% url 'ListCommande' %}">List Commandes</a>
            <a class="dropdown-item" href="{% url 'create_commande' %}">Ajout commande</a>
        </div>
      </li>
      {% endif %}
      {% if user.is_authenticated and not user.is_staff %}
      <li class="nav-item  ">
        <a class="nav-link" href="{% url 'indexA' %}">Contact </a>
      </li>
      {% endif %}
      
    </ul>
    <ul class="navbar-nav mr-auto">
      
      {% if user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link" href="#">{{user}}</a>
      </li>
          
          
          <li class="nav-item">
          <a   class="nav-link" href="{% url 'logout' %}">Déconnexion</a>
          </li>


          {% else %}
          <li class="nav-item">
          <a href="{% url 'login' %}">Connexion</a>
          </li>
          <li class="nav-link">
          <a  class="nav-link" href="{% url 'register' %}">Inscription</a>
          </li>
          {% endif %}
        </ul>
        

        <form method="GET" action="{% url 'search' %}" class="form-inline my-2 my-lg-0">
          <div class="input-group">
            <input type="text" name="q" placeholder="Recherche d'un produit..." class="form-control border-0 rounded-0 py-2" aria-label="Search">
            <div class="input-group-append">
              <button type="submit" class="btn btn-outline-secondary border-0 rounded-0 py-2">Recherche</button>
            </div>
          </div>
        </form>
        
        
          
        </div>
      </div>
       </nav>
    </div>
  </div>
  {% block content %}
  
  {% endblock %}
</head>
<style>
  .navbar {
    background-color: #ffcc00;
  }
  
  .navbar-brand {
    font-weight: bold;
  }
  
  .navbar-toggler {
    border-color: #fff;
  }
  
  .navbar-toggler-icon {
    background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3e%3cpath stroke='rgba(255, 255, 255, 1.0)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
  }
  
  .navbar-nav .nav-item .nav-link {
    color: #15526;
  }
  
  .navbar-nav .nav-item .nav-link:hover {
    color: #15526;
    border-bottom: 2px solid #fff;
  }
  
  .navbar-nav .nav-item.active .nav-link {
    color: #15526;
    border-bottom: 2px solid #fff;
  }
  
  .dropdown-menu {
    background-color: #414a5c;
  }
  
  .dropdown-menu .dropdown-item {
    color: #fff;
  }
  
  .dropdown-menu .dropdown-item:hover {
    color: #fff;
    background-color: #313a46;
  }
  
  .dropdown-menu .dropdown-divider {
    background-color: #fff;
  }
  
  .form-inline .form-control {
    border-color: #fff;
  }
  
  .form-inline .form-control:focus {
    border-color: #fff;
    box-shadow: none;
  }
  
  .form-inline .btn-primary {
    background-color: #fff;
    border-color: #fff;
    color: #414a5c;
  }
  
  .form-inline .btn-primary:hover {
    background-color: #fff;
    border-color: #fff;
    color: #414a5c;
  }
  
</style>
</html>

magasin/templates/magasin/contact.html
{% extends 'magasin/base.html' %}
{% block title %} Home Page {% endblock %}
{% block content %}
<!-- body -->
    <div class="container">
      <form class="form" action="{% url 'indexA' %}" method="POST">
        {% csrf_token %}
        <h1 class="form-title">Message me </h1>
        <div class="grid">
          <div class="form-group">
            <input type="text" name="name" id="name" placeholder="Full name">
          </div>
          <div class="form-group">
            <input type="email" name="email" id="email" placeholder="Your email">
          </div>
          <div class="form-group">
            <input type="text" name="subject" id="subject" placeholder="Subject">
          </div>
          <div class="form-group">
            <textarea name="message" id="message" placeholder="Your message goes here"></textarea>
          </div>
          <button type="submit" class="btn">Send message</button>
        </div>
      </form>
    </div>
    
      
      <!--Google Maps-->
<!--Section: Contact v.2-->
<style>
    
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      
      body {
        font-family: Montserrat, "sans-serif";
        background-color: #f4f4f4;
        font-weight: 400;
        padding:5%;
      }
      
      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 0 32px;
      }
      
      .grid {
        display: grid;
        column-gap: 80px;
        row-gap: 24px;
        align-items: end;
      }
      
      .form {
        width: 100%;
        max-width: 400px;
        margin: 64px auto 0;
        background-color: #fff;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
        padding: 24px 32px;
        border-radius: 11px;
      
        .form-title {
          font-size: 28px;
          font-weight: 700;
          color: #21325e;
          text-align: center;
          margin-bottom: 32px;
        }
      
        .form-group {
          margin-bottom: 24px;
      
          input,
          textarea {
            display: inline-block;
            width: 100%;
            padding: 16px 8px;
            font-family: inherit;
            font-size: 14px;
            color: #000 !important;
            border: none;
            outline: none;
      
            &::placeholder {
              color: #37595e;
            }
      
            &:focus {
              border-color: #21325e;
            }
          }
      
          input {
            border-bottom: 1px solid #ddd;
          }
      
          textarea {
            border: 1px solid #ddd;
            height: 100px;
            resize: none;
            border-radius: 11px;
          }
        }
        .btn {
          display: inline-block;
          border: none;
          outline: none;
          background-color: #ffcc00;
          color: #fff;
          font-family: inherit;
          font-size: 14px;
          padding: 16px 32px;
          border-radius: 1000px;
          cursor: pointer;
        }
        .btn:hover{
            background-color: #155263;
        }
        
      }
      
      @media screen and (min-width: 768px) {
        .grid {
          grid-template-columns: 1fr 1fr;
        }
      
        .form {
          max-width: 800px;
        }
      
        .btn {
          grid-column: 1 / -1;
          justify-self: end;
        }
      }
      
</style>
</div>

{% endblock %}

magasin/templates/magasin/product.detail.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ produit.libellé }}</h1>
    <p>{{ produit.description }}</p>
    <p>Prix: {{ produit.prix }}</p>
    <p>Catégorie: {{ produit.Categorie }}</p>
    <p>Type: {{ produit.get_type_display }}</p>

    <form method="post" action="{% url 'monapp:add_to_cart' produit.id %}">
        {% csrf_token %}
        <button type="submit">{% if produit in cart.produits.all %}Supprimer du panier{% else %}Ajouter au panier{% endif %}</button>
    </form>
{% endblock %}